---
abstract: 'Perl class for creating image from images directory.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-Select
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.03
  Error::Pure: 0.11
  File::Basename: 0
  Imager: 0
  List::MoreUtils: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Image-Select
  homepage: https://github.com/tupinek/Image-Select
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Image-Select
version: '0.01'
